### importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

### **Loading the data**

In [2]:
data_preprocessed = pd.read_csv("/content/drive/MyDrive/Udemy Courses/DATA SCIENCE COURSE/Absenteesim Data/Absenteeism_preprocessed.csv")

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  ...  Children  Pet  Absenteeism Time in Hours
0         0         0         0  ...         2    1                          4
1         0         0         0  ...         1    0                          0
2         0         0         0  ...         0    0                          2
3         1         0         0  ...         2    0                          4
4         0         0         0  ...         2    1                          2

[5 rows x 15 columns]

### Create the target

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [6]:
len(targets)

700

In [7]:
data_preprocessed['Excessive Absenteesim'] = targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  ...  Absenteeism Time in Hours  Excessive Absenteesim
0         0         0  ...                          4                      1
1         0         0  ...                          0                      0
2         0         0  ...                          2                      0
3         1         0  ...                          4                      1
4         0         0  ...                          2                      0

[5 rows x 16 columns]

### comment on the targets

In [9]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week','Distance to Work','Daily Work Load Average'],axis=1)

In [11]:
data_preprocessed is data_with_targets

False

### Selecting the inputs for regression

In [12]:
data_with_targets.shape

(700, 12)

In [13]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
unscaled_inputs.head()

Reason_1  Reason_2  Reason_3  ...  Education  Children  Pet
0         0         0         0  ...          0         2    1
1         0         0         0  ...          0         1    0
2         0         0         0  ...          0         0    0
3         1         0         0  ...          0         2    0
4         0         0         0  ...          0         2    1

[5 rows x 11 columns]

### Standardize the data

In [14]:
from sklearn.preprocessing import StandardScaler

# absenteeism_scaler = StandardScaler()


In [15]:
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler 

class CustomScaler(BaseEstimator,TransformerMixin):
  def __init__(self,columns,copy=True,with_mean=True,with_std=True):
    self.scaler = StandardScaler(copy,with_mean,with_std)
    self.columns = columns
    self.mean_ = None
    self.var_ = None
  
  def fit(self,X,y= None):
    self.scaler.fit(X[self.columns],y)
    self.mean_ = np.mean(X[self.columns])
    self.var_ = np.var(X[self.columns])
    return self
  
  def transform(self,X,y=None,copy=None):
    init_col_order = X.columns
    X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]),columns=self.columns)
    X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
    return pd.concat([X_not_scaled,X_scaled],axis=1)[init_col_order]

In [16]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [20]:
# columns_to_scale = ['Month Value',
#        'Day of the Week', 'Transportation Expense', 'Distance to Work',
#        'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
#        'Children', 'Pet']
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [21]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [22]:
absenteeism_scaler.fit(unscaled_inputs)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pet'],
             copy=None, with_mean=None, with_std=None)

In [23]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [24]:
scaled_inputs.shape

(700, 11)

In [25]:
scaled_inputs

Reason_1  Reason_2  Reason_3  ...  Education  Children       Pet
0           0         0         0  ...          0  0.880469  0.268487
1           0         0         0  ...          0 -0.019280 -0.589690
2           0         0         0  ...          0 -0.919030 -0.589690
3           1         0         0  ...          0  0.880469 -0.589690
4           0         0         0  ...          0  0.880469  0.268487
..        ...       ...       ...  ...        ...       ...       ...
695         1         0         0  ...          1  0.880469 -0.589690
696         1         0         0  ...          0 -0.019280  1.126663
697         1         0         0  ...          1 -0.919030 -0.589690
698         0         0         0  ...          1 -0.919030 -0.589690
699         0         0         0  ...          0 -0.019280  0.268487

[700 rows x 11 columns]

### Splitting the dataset to train and test

In [26]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(scaled_inputs,targets,train_size=0.8,shuffle=True,random_state=20)

In [27]:
[X_train.shape,y_train.shape,X_test.shape,y_test.shape]

[(560, 11), (560,), (140, 11), (140,)]

### Fitting the model and Checking its accuracy

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [29]:
reg = LogisticRegression()

In [30]:
reg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
reg.score(X_train,y_train)

0.7767857142857143

### Manually checking the accuracy

In [32]:
model_output = reg.predict(X_train)

In [33]:
model_output

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [34]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [35]:
model_output == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [36]:
np.sum((model_output==y_train))

435

In [37]:
model_output.shape[0]

560

In [38]:
np.sum((model_output==y_train))/model_output.shape[0]

0.7767857142857143

### Creating a summary table 

In [39]:
reg.intercept_

array([-1.60957471])

In [40]:
reg.coef_

array([[ 2.77151176,  0.93168817,  3.09210221,  0.8090592 ,  0.00781237,
         0.62505482, -0.17390339,  0.28829409, -0.24081615,  0.35753531,
        -0.27337422]])

In [41]:
feature_name = unscaled_inputs.columns.values

In [42]:
summary_table = pd.DataFrame(columns=['Feature name'],data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 Reason_1     2.771512
1                 Reason_2     0.931688
2                 Reason_3     3.092102
3                 Reason_4     0.809059
4              Month Value     0.007812
5   Transportation Expense     0.625055
6                      Age    -0.173903
7          Body Mass Index     0.288294
8                Education    -0.240816
9                 Children     0.357535
10                     Pet    -0.273374

In [43]:
summary_table.index = summary_table.index+1

In [44]:
summary_table.loc[0] = ['intercept',reg.intercept_[0]]

In [45]:
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                intercept    -1.609575
1                 Reason_1     2.771512
2                 Reason_2     0.931688
3                 Reason_3     3.092102
4                 Reason_4     0.809059
5              Month Value     0.007812
6   Transportation Expense     0.625055
7                      Age    -0.173903
8          Body Mass Index     0.288294
9                Education    -0.240816
10                Children     0.357535
11                     Pet    -0.273374

### interpreting the coefficients

In [46]:
summary_table['Odds_Ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds_Ratio
0                intercept    -1.609575    0.199973
1                 Reason_1     2.771512   15.982778
2                 Reason_2     0.931688    2.538791
3                 Reason_3     3.092102   22.023327
4                 Reason_4     0.809059    2.245794
5              Month Value     0.007812    1.007843
6   Transportation Expense     0.625055    1.868348
7                      Age    -0.173903    0.840378
8          Body Mass Index     0.288294    1.334150
9                Education    -0.240816    0.785986
10                Children     0.357535    1.429801
11                     Pet    -0.273374    0.760808

In [47]:
summary_table.sort_values('Odds_Ratio',ascending=False)

Feature name  Coefficient  Odds_Ratio
3                 Reason_3     3.092102   22.023327
1                 Reason_1     2.771512   15.982778
2                 Reason_2     0.931688    2.538791
4                 Reason_4     0.809059    2.245794
6   Transportation Expense     0.625055    1.868348
10                Children     0.357535    1.429801
8          Body Mass Index     0.288294    1.334150
5              Month Value     0.007812    1.007843
7                      Age    -0.173903    0.840378
9                Education    -0.240816    0.785986
11                     Pet    -0.273374    0.760808
0                intercept    -1.609575    0.199973

### Testing the model

In [48]:
reg.score(X_test,y_test)

0.7357142857142858

In [49]:
predicted_proba = reg.predict_proba(X_test)
predicted_proba

array([[0.75466347, 0.24533653],
       [0.60917591, 0.39082409],
       [0.48329093, 0.51670907],
       [0.75768232, 0.24231768],
       [0.08357741, 0.91642259],
       [0.3052464 , 0.6947536 ],
       [0.303675  , 0.696325  ],
       [0.11636888, 0.88363112],
       [0.7400284 , 0.2599716 ],
       [0.75596036, 0.24403964],
       [0.50609784, 0.49390216],
       [0.19501503, 0.80498497],
       [0.06248668, 0.93751332],
       [0.7055465 , 0.2944535 ],
       [0.29675526, 0.70324474],
       [0.52028649, 0.47971351],
       [0.50551315, 0.49448685],
       [0.50843643, 0.49156357],
       [0.36713074, 0.63286926],
       [0.06422143, 0.93577857],
       [0.73822433, 0.26177567],
       [0.75768232, 0.24231768],
       [0.47994423, 0.52005577],
       [0.47760936, 0.52239064],
       [0.22619725, 0.77380275],
       [0.74047815, 0.25952185],
       [0.51148533, 0.48851467],
       [0.87702735, 0.12297265],
       [0.24005377, 0.75994623],
       [0.75768232, 0.24231768],
       [0.

### Save the Model

In [50]:
import pickle

In [52]:
with open('/content/drive/MyDrive/Udemy Courses/DATA SCIENCE COURSE/Absenteesim Data/model','wb') as file:
  pickle.dump(reg,file)

In [53]:
with open('/content/drive/MyDrive/Udemy Courses/DATA SCIENCE COURSE/Absenteesim Data/scaler','wb') as file:
  pickle.dump(absenteeism_scaler,file)